### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by rockywind** [TRAILab/CaDDN#24]
`Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    'src/sampling_gpu.cu',
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
`
When I runs the `python setup.py develop`, I met the probelm.
My environment is that
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
`
**and my pytorch installed is `conda install pytorch==1.5.0 torchvision==0.6.0 cudatoolkit=10.2 -c pytorch`**

**Comment by IssamLaradji** [comment]
how did you solve it @rockywind ?

**Comment by rockywind** [comment]
Sorry for the late.I reinstall it follow the guide[](https://github.com/TRAILab/CaDDN/blob/master/docs/INSTALL.md)
